"""initial_technicians_assignments

Revision ID: b76286bc7620
Revises: 
Create Date: 2026-04-02 14:03:26.870036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b76286bc7620'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technicians',
    sa.Column('tech_id', sa.String(length=128), nullable=False),
    sa.Column('tech_name', sa.String(length=256), nullable=False),
    sa.Column('available_am', sa.Boolean(), nullable=False),
    sa.Column('available_mid', sa.Boolean(), nullable=False),
    sa.Column('available_pm', sa.Boolean(), nullable=False),
    sa.Column('staff_status', sa.Enum('scheduled', 'call_off', 'overtime', name='staffing_status', native_enum=False, length=32), nullable=False),
    sa.Column('daily_preference', sa.Enum('consistency', 'variation', name='dailypreference', native_enum=False, length=32), nullable=False),
    sa.Column('favorites', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('dislikes', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('tech_id'),
    sa.UniqueConstraint('tech_name', name='uq_technicians_tech_name')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('technician_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=256), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.Enum('AM', 'MID', 'PM', name='timeslot', native_enum=False, length=8), nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', name='assignmentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.tech_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_status_work_date', 'assignments', ['status', 'work_date'], unique=False)
    op.create_index('ix_assignments_tech_work_status', 'assignments', ['technician_id', 'work_date', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignments_tech_work_status', table_name='assignments')
    op.drop_index('ix_assignments_status_work_date', table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('technicians')
    # ### end Alembic commands ###
